

const meetings = [
    {
        users: [2, 4],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 2, 14, 30),
        endMeetingTime: new Date(2018, 1, 2, 16, 30),
        meetingLocation: "Culture Espresso, 247 W 36th St",
        meetingTheme: "Potential Merger",
        approved: true,
        initiator: 2,
        requestedTime:new Date(2018, 1, 1, 14, 30),
    },
    {
        users: [5, 9],
        meetingType: ["Drink",],
        begMeetingTime: new Date(2018, 1, 3, 19, 30),
        endMeetingTime: new Date(2018, 1, 3, 21, 30),
        meetingLocation: "Maison Premiere, 344 Bowery",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 5,
        requestedTime:new Date(2018, 1, 1, 15, 30),
    },
    {
        users: [1,5],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 2, 17, 30),
        endMeetingTime: new Date(2018, 1, 2, 19, 30),
        meetingLocation: "Box Kite Coffee, 700 E 9th St",
        meetingTheme: "Prep for road trip",
        approved: true,
        initiator: 1,

        requestedTime:new Date(2018, 1, 1, 15, 30),
    },

     {
        users: [4, 9],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 1, 10, 30),
        endMeetingTime: new Date(2018, 1, 1, 12, 30),
        meetingLocation: "The Winslow, 55 243 E 14th St",
        meetingTheme: "Prep for Investor Presentation",
        approved: false,
        initiator: 4,
        requestedTime:new Date(2018, 1, 2, 14, 30),
    },

    {
        users: [3, 2],
        meetingType: ["Drink",],
        begMeetingTime: new Date(2018, 1, 3, 19, 30),
        endMeetingTime: new Date(2018, 1, 3, 21, 30),
        meetingLocation: "Maison Premiere, 344 Bowery",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 3,
        requestedTime:new Date(2018, 1, 2, 15, 30),
    },

    {
        users: [3, 9],
        meetingType: ["Drink",],
        begMeetingTime: new Date(2018, 1, 5, 17, 30),
        endMeetingTime: new Date(2018, 1, 5, 19, 30),
        meetingLocation: "Dear Irving, 55 Irving Pl",
        meetingTheme: "Hang Out",
        approved: true,
        initiator: 9,

        requestedTime:new Date(2018, 1, 3, 14, 30),
    },

    {
        users: [4,5],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 5, 10, 30),
        endMeetingTime: new Date(2018, 1, 5, 12, 30),
        meetingLocation: "The Winslow, 55 243 E 14th St",
        meetingTheme: "Prep for Investor Presentation",
        approved: true,
        initiator: 4,
        requestedTime:new Date(2018, 1, 3, 15, 30),
    },
    {
        users: [5, 9],
        meetingType: ["Skype",],
        begMeetingTime: new Date(2018, 1, 6, 10, 30),
        endMeetingTime: new Date(2018, 1, 6, 12, 30),
        meetingLocation: "any where",
        meetingTheme: "Sale's prospecting",
        approved: true,
        initiator: 5,
        requestedTime:new Date(2018, 1, 3, 16, 30),
    },

    {
        users: [6, 7],
        meetingType: ["Dinner",],
        begMeetingTime: new Date(2018, 1, 7, 16, 30),
        endMeetingTime: new Date(2018, 1, 7, 12, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Client meet up",
        approved: true,
        initiator: 6,
        requestedTime:new Date(2018, 1, 4, 14, 30),

    },

    {
        users: [10, 7],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 7, 13, 30),
        endMeetingTime: new Date(2018, 1, 7, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: true,
        initiator: 7,
        requestedTime:new Date(2018, 1, 4, 10, 30),
    },

     {
        users: [1, 7],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 8, 13, 30),
        endMeetingTime: new Date(2018, 1, 8, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 7,
        requestedTime:new Date(2018, 1, 4, 15, 30),
    },

        {
        users: [1, 9],
        meetingType: ["Skype",],
        begMeetingTime: new Date(2018, 1, 6, 10, 30),
        endMeetingTime: new Date(2018, 1, 6, 12, 30),
        meetingLocation: "any where",
        meetingTheme: "Sale's prospecting",
        approved: false,
        initiator: 9,
        requestedTime:new Date(2018, 1, 5, 14, 30),
    },

    {
        users: [6, 10],
        meetingType: ["Breakfast",],
        begMeetingTime: new Date(2018, 1, 9, 9, 30),
        endMeetingTime: new Date(2018, 1, 9, 10, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Client meet up",
        approved: true,
        initiator: 10,
        requestedTime:new Date(2018, 1, 5, 12, 30),
    },

    {
        users: [10, 7],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 7, 13, 30),
        endMeetingTime: new Date(2018, 1, 7, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 7,
        requestedTime:new Date(2018, 1, 5, 13, 30),
    },

     {
        users: [1, 7],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 8, 13, 30),
        endMeetingTime: new Date(2018, 1, 8, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 7,
        requestedTime:new Date(2018, 1, 5, 16, 30),
    },

         {
        users: [1, 3],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 8, 13, 30),
        endMeetingTime: new Date(2018, 1, 8, 14, 30),
        meetingLocation: "Goodnight Sonny,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 7,
        requestedTime:new Date(2018, 1, 6, 14, 30),
    },

        {
        users: [1, 4],
        meetingType: ["Regular Meeting",],
        begMeetingTime: new Date(2018, 1, 6, 10, 30),
        endMeetingTime: new Date(2018, 1, 6, 12, 30),
        meetingLocation: "Company Headquarter",
        meetingTheme: "Sale's prospecting",
        approved: false,
        initiator: 4,
        requestedTime:new Date(2018, 1, 6, 15, 30),
    },

    {
        users: [1, 5],
        meetingType: ["Breakfast",],
        begMeetingTime: new Date(2018, 1, 9, 9, 30),
        endMeetingTime: new Date(2018, 1, 9, 10, 30),
        meetingLocation: "The Garret,531 E 5th St",
        meetingTheme: "Client meet up",
        approved: false,
        initiator: 5,
        requestedTime:new Date(2018, 1, 6, 16, 30),
    },

    {
        users: [2, 7],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 10, 13, 30),
        endMeetingTime: new Date(2018, 1, 10, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 7,
        requestedTime:new Date(2018, 1, 6, 17, 30),
    },

     {
        users: [2, 10],
        meetingType: ["Lunch",],
        begMeetingTime: new Date(2018, 1, 10, 13, 30),
        endMeetingTime: new Date(2018, 1, 10, 14, 30),
        meetingLocation: "The Wayland,531 E 5th St",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 2,
        requestedTime:new Date(2018, 1, 6, 18, 30),
    },

        {
        users: [3, 4],
        meetingType: ["Drink",],
        begMeetingTime: new Date(2018, 1, 11, 19, 30),
        endMeetingTime: new Date(2018, 1, 11, 21, 30),
        meetingLocation: "Maison Premiere, 344 Bowery",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 4,
        requestedTime:new Date(2018, 1, 7, 14, 30),
    },
    {
        users: [3,5],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 11, 17, 30),
        endMeetingTime: new Date(2018, 1, 11, 19, 30),
        meetingLocation: "Box Kite Coffee, 700 E 9th St",
        meetingTheme: "Prep for road trip",
        approved: true,
        initiator: 5,
        requestedTime:new Date(2018, 1, 8, 14, 30),
    },

     {
        users: [4, 5],
        meetingType: ["Regular Meeting",],
        begMeetingTime: new Date(2018, 1, 12, 10, 30),
        endMeetingTime: new Date(2018, 1, 12, 12, 30),
        meetingLocation: "The Winslow, 55 243 E 14th St",
        meetingTheme: "Prep for Investor Presentation",
        approved: false,
        initiator: 4,
        requestedTime:new Date(2018, 1, 8, 4, 30),
    },

    {
        users: [4, 6],
        meetingType: ["Regular Meeting",],
        begMeetingTime: new Date(2018, 1, 13, 19, 30),
        endMeetingTime: new Date(2018, 1, 13, 21, 30),
        meetingLocation: "Sake Bar Decibel, 344 Bowery",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 6,
        requestedTime:new Date(2018, 1, 8, 10, 30),
    },
        {
        users: [3,5],
        meetingType: ["Regular Meeting",],
        begMeetingTime: new Date(2018, 1, 14, 17, 30),
        endMeetingTime: new Date(2018, 1, 14, 19, 30),
        meetingLocation: "Box Kite Coffee, 700 E 9th St",
        meetingTheme: "Prep for road trip",
        approved: true,
        initiator: 5,
        requestedTime:new Date(2018, 1, 8, 16, 30),
    },

     {
        users: [4, 5],
        meetingType: ["Coffee",],
        begMeetingTime: new Date(2018, 1, 14, 10, 30),
        endMeetingTime: new Date(2018, 1, 14, 12, 30),
        meetingLocation: "The Winslow, 55 243 E 14th St",
        meetingTheme: "Prep for Investor Presentation",
        approved: false,
        initiator: 4,
        requestedTime:new Date(2018, 1, 9, 14, 30),
    },

    {
        users: [4, 6],
        meetingType: ["Regular Meeting",],
        begMeetingTime: new Date(2018, 1, 15, 19, 30),
        endMeetingTime: new Date(2018, 1, 15, 21, 30),
        meetingLocation: "Sake Bar Decibel, 344 Bowery",
        meetingTheme: "Catching up",
        approved: false,
        initiator: 6,
        requestedTime:new Date(2018, 1, 10, 14, 30),
    },

];
module.exports = meetings;